unit:
	g++ -o test -I ../include ../test/UnitTest.cpp BookingClasses.cpp Divyaang.cpp Booking.cpp BookingCategory.cpp Gender.cpp Date.cpp Concessions.cpp Station.cpp Railways.cpp Passenger.cpp Name.cpp
app:
	g++ -o test -I ../include ../test/Application.cpp BookingClasses.cpp Divyaang.cpp Booking.cpp BookingCategory.cpp Gender.cpp Date.cpp Concessions.cpp Station.cpp Railways.cpp Passenger.cpp Name.cpp
sampleApp:
	g++ -o test -I ../include BookingClasses.cpp Divyaang.cpp Booking.cpp BookingCategory.cpp Gender.cpp Date.cpp Concessions.cpp Station.cpp Railways.cpp Passenger.cpp Name.cpp
